<a href="https://colab.research.google.com/github/oviccenzo/inteligencia-artificial/blob/main/datasest_de_todos_os_dados_dos_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Imersão dev alura ciencia de dados para python

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("dados-imersao-final.csv")

In [ ]:
df

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,residencia_iso3
0,2025,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media,USA
1,2025,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media,USA
2,2025,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media,AUS
3,2025,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media,AUS
4,2025,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
133334,2020,senior,integral,Data Scientist,412000,USD,412000,US,remoto,US,grande,USA
133335,2021,pleno,integral,Principal Data Scientist,151000,USD,151000,US,remoto,US,grande,USA
133336,2020,junior,integral,Data Scientist,105000,USD,105000,US,remoto,US,pequena,USA
133337,2020,junior,contrato,Business Data Analyst,100000,USD,100000,US,remoto,US,grande,USA
133338,2021,senior,integral,Data Scientist,7000000,INR,94665,IN,hibrido,IN,grande,IND

In [ ]:
print(df.corr)

<bound method DataFrame.corr of          ano senioridade  contrato                     cargo  salario moeda  \
0       2025      senior  integral        Solutions Engineer   214000   USD
1       2025      senior  integral        Solutions Engineer   136000   USD
2       2025       pleno  integral             Data Engineer   158800   USD
3       2025       pleno  integral             Data Engineer   139200   USD
4       2025      junior  integral             Data Engineer    90000   USD
...      ...         ...       ...                       ...      ...   ...
133334  2020      senior  integral            Data Scientist   412000   USD
133335  2021       pleno  integral  Principal Data Scientist   151000   USD
133336  2020      junior  integral            Data Scientist   105000   USD
133337  2020      junior  contrato     Business Data Analyst   100000   USD
133338  2021      senior  integral            Data Scientist  7000000   INR

           usd residencia      remoto empresa tamanho_empresa residencia_iso3
0       214000         US      remoto      US           media             USA
1       136000         US      remoto      US           media             USA
2       158800         AU  presencial      AU           media             AUS
3       139200         AU  presencial      AU           media             AUS
4        90000         US  presencial      US           media             USA
...        ...        ...         ...     ...             ...             ...
133334  412000         US      remoto      US          grande             USA
133335  151000         US      remoto      US          grande             USA
133336  105000         US      remoto      US         pequena             USA
133337  100000         US      remoto      US          grande             USA
133338   94665         IN     hibrido      IN          grande             IND

[133339 rows x 12 columns]>

In [ ]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,residencia_iso3
0,2025,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media,USA
1,2025,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media,USA
2,2025,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media,AUS
3,2025,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media,AUS
4,2025,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media,USA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133339 entries, 0 to 133338
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  int64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
 11  residencia_iso3  133337 non-null  object
dtypes: int64(3), object(9)
memory usage: 12.2+ MB

In [ ]:
print(df.abs)

<bound method NDFrame.abs of          ano senioridade  contrato                     cargo  salario moeda  \
0       2025      senior  integral        Solutions Engineer   214000   USD
1       2025      senior  integral        Solutions Engineer   136000   USD
2       2025       pleno  integral             Data Engineer   158800   USD
3       2025       pleno  integral             Data Engineer   139200   USD
4       2025      junior  integral             Data Engineer    90000   USD
...      ...         ...       ...                       ...      ...   ...
133334  2020      senior  integral            Data Scientist   412000   USD
133335  2021       pleno  integral  Principal Data Scientist   151000   USD
133336  2020      junior  integral            Data Scientist   105000   USD
133337  2020      junior  contrato     Business Data Analyst   100000   USD
133338  2021      senior  integral            Data Scientist  7000000   INR

           usd residencia      remoto empresa tamanho_empresa residencia_iso3
0       214000         US      remoto      US           media             USA
1       136000         US      remoto      US           media             USA
2       158800         AU  presencial      AU           media             AUS
3       139200         AU  presencial      AU           media             AUS
4        90000         US  presencial      US           media             USA
...        ...        ...         ...     ...             ...             ...
133334  412000         US      remoto      US          grande             USA
133335  151000         US      remoto      US          grande             USA
133336  105000         US      remoto      US         pequena             USA
133337  100000         US      remoto      US          grande             USA
133338   94665         IN     hibrido      IN          grande             IND

[133339 rows x 12 columns]>

In [ ]:
print(df.value_counts())

ano   senioridade  contrato  cargo                        salario  moeda  usd     residencia  remoto      empresa  tamanho_empresa  residencia_iso3
2025  senior       integral  Data Scientist               160000   USD    160000  US          remoto      US       media            USA                194
                                                          110000   USD    110000  US          remoto      US       media            USA                186
2024  senior       integral  Data Scientist               160000   USD    160000  US          remoto      US       media            USA                182
                                                          110000   USD    110000  US          remoto      US       media            USA                168
                             Machine Learning Researcher  160000   USD    160000  US          remoto      US       media            USA                161
                                                                                                                                                      ...
2020  junior       integral  Data Analyst                 42000    EUR    47899   DE          presencial  DE       grande           DEU                  1
                                                          20000    EUR    22809   PT          remoto      PT       media            PRT                  1
                             Big Data Engineer            70000    USD    70000   US          remoto      US       grande           USA                  1
                             Azure Data Engineer          100000   USD    100000  MU          presencial  MU       pequena          MUS                  1
                             AI Scientist                 300000   DKK    45896   DK          hibrido     DK       pequena          DNK                  1
Name: count, Length: 64615, dtype: int64

In [ ]:
print(df.describe())

                 ano       salario            usd
count  133339.000000  1.333390e+05  133339.000000
mean     2024.358770  1.632846e+05  157619.079339
std         0.680627  2.173937e+05   74289.262933
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060065e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

In [ ]:
print(df.tail)

<bound method NDFrame.tail of          ano senioridade  contrato                     cargo  salario moeda  \
0       2025      senior  integral        Solutions Engineer   214000   USD
1       2025      senior  integral        Solutions Engineer   136000   USD
2       2025       pleno  integral             Data Engineer   158800   USD
3       2025       pleno  integral             Data Engineer   139200   USD
4       2025      junior  integral             Data Engineer    90000   USD
...      ...         ...       ...                       ...      ...   ...
133334  2020      senior  integral            Data Scientist   412000   USD
133335  2021       pleno  integral  Principal Data Scientist   151000   USD
133336  2020      junior  integral            Data Scientist   105000   USD
133337  2020      junior  contrato     Business Data Analyst   100000   USD
133338  2021      senior  integral            Data Scientist  7000000   INR

           usd residencia      remoto empresa tamanho_empresa residencia_iso3
0       214000         US      remoto      US           media             USA
1       136000         US      remoto      US           media             USA
2       158800         AU  presencial      AU           media             AUS
3       139200         AU  presencial      AU           media             AUS
4        90000         US  presencial      US           media             USA
...        ...        ...         ...     ...             ...             ...
133334  412000         US      remoto      US          grande             USA
133335  151000         US      remoto      US          grande             USA
133336  105000         US      remoto      US         pequena             USA
133337  100000         US      remoto      US          grande             USA
133338   94665         IN     hibrido      IN          grande             IND

[133339 rows x 12 columns]>

In [ ]:
print(df)

         ano senioridade  contrato                     cargo  salario moeda  \
0       2025      senior  integral        Solutions Engineer   214000   USD
1       2025      senior  integral        Solutions Engineer   136000   USD
2       2025       pleno  integral             Data Engineer   158800   USD
3       2025       pleno  integral             Data Engineer   139200   USD
4       2025      junior  integral             Data Engineer    90000   USD
...      ...         ...       ...                       ...      ...   ...
133334  2020      senior  integral            Data Scientist   412000   USD
133335  2021       pleno  integral  Principal Data Scientist   151000   USD
133336  2020      junior  integral            Data Scientist   105000   USD
133337  2020      junior  contrato     Business Data Analyst   100000   USD
133338  2021      senior  integral            Data Scientist  7000000   INR

           usd residencia      remoto empresa tamanho_empresa residencia_iso3
0       214000         US      remoto      US           media             USA
1       136000         US      remoto      US           media             USA
2       158800         AU  presencial      AU           media             AUS
3       139200         AU  presencial      AU           media             AUS
4        90000         US  presencial      US           media             USA
...        ...        ...         ...     ...             ...             ...
133334  412000         US      remoto      US          grande             USA
133335  151000         US      remoto      US          grande             USA
133336  105000         US      remoto      US         pequena             USA
133337  100000         US      remoto      US          grande             USA
133338   94665         IN     hibrido      IN          grande             IND

[133339 rows x 12 columns]

In [ ]:
df['ano'].mean()

np.float64(2024.3587697522855)

In [ ]:
df['ano'].sum()

np.int64(269925974)

In [ ]:
df['ano'].std()

0.6806266087844866

In [ ]:
df['ano'].median()

2024.0

In [ ]:
df['ano'].max()

2025

In [ ]:
df['ano'].tail()

133334    2020
133335    2021
133336    2020
133337    2020
133338    2021
Name: ano, dtype: int64

In [ ]:
df['ano'].value_counts()

ano
2024    62240
2025    60627
2023     8521
2022     1660
2021      216
2020       75
Name: count, dtype: int64

#Exemplo detecção de anomalia

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("transacoes_anomalias.csv")

In [ ]:
(df)

     valor  frequencia  tempo_entre_compras    categoria
0   169.87          13                  9.1    vestuario
1   144.47          18                  8.1  eletronicos
2   175.91           9                  9.7  alimentacao
3   210.92           5                 12.1  eletronicos
4   140.63           7                  6.4  alimentacao
..     ...         ...                  ...          ...
95  724.38           1                 32.2  alimentacao
96  935.53           2                 35.2  eletronicos
97  931.33           2                 26.9  eletronicos
98  900.61           1                 27.8  eletronicos
99  871.85           1                 21.7  eletronicos

[100 rows x 4 columns]

In [ ]:
(df.tail())

     valor  frequencia  tempo_entre_compras    categoria
95  724.38           1                 32.2  alimentacao
96  935.53           2                 35.2  eletronicos
97  931.33           2                 26.9  eletronicos
98  900.61           1                 27.8  eletronicos
99  871.85           1                 21.7  eletronicos

In [ ]:
(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   valor                100 non-null    float64
 1   frequencia           100 non-null    int64
 2   tempo_entre_compras  100 non-null    float64
 3   categoria            100 non-null    object
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB

In [ ]:
(df.describe())

             valor  frequencia  tempo_entre_compras
count   100.000000  100.000000            100.00000
mean    219.652400    9.820000              9.91900
std     225.978833    4.963259              8.01444
min      45.210000    1.000000              3.40000
25%     128.042500    6.000000              6.27500
50%     153.090000   10.000000              7.55000
75%     182.885000   14.000000              9.10000
max    1016.240000   19.000000             41.90000

In [ ]:
(df.value_counts())

valor    frequencia  tempo_entre_compras  categoria
45.21    7           4.7                  alimentacao    1
70.50    8           5.9                  alimentacao    1
71.61    5           6.9                  alimentacao    1
73.47    8           8.7                  alimentacao    1
79.48    15          6.0                  eletronicos    1
                                                        ..
900.61   1           27.8                 eletronicos    1
911.65   2           41.9                 eletronicos    1
931.33   2           26.9                 eletronicos    1
935.53   2           35.2                 eletronicos    1
1016.24  1           39.2                 vestuario      1
Name: count, Length: 100, dtype: int64

In [ ]:
(df.value_counts())

valor    frequencia  tempo_entre_compras  categoria
45.21    7           4.7                  alimentacao    1
70.50    8           5.9                  alimentacao    1
71.61    5           6.9                  alimentacao    1
73.47    8           8.7                  alimentacao    1
79.48    15          6.0                  eletronicos    1
                                                        ..
900.61   1           27.8                 eletronicos    1
911.65   2           41.9                 eletronicos    1
931.33   2           26.9                 eletronicos    1
935.53   2           35.2                 eletronicos    1
1016.24  1           39.2                 vestuario      1
Name: count, Length: 100, dtype: int64

In [ ]:
df['frequencia'].mean()

np.float64(9.82)

In [ ]:
df['frequencia'].max()

19

In [ ]:
df['frequencia'].tail()

95    1
96    2
97    2
98    1
99    1
Name: frequencia, dtype: int64

In [ ]:
df['frequencia'].median()

10.0

In [ ]:
df['frequencia'].count()

np.int64(100)

In [ ]:
(df['frequencia'].value_counts())

frequencia
5     13
8      8
15     8
12     7
7      7
10     7
6      6
11     6
16     6
1      6
9      5
13     4
18     4
19     4
14     4
2      4
17     1
Name: count, dtype: int64

In [ ]:
df['frequencia'].sum()

np.int64(982)

In [ ]:
df['frequencia'].std()

4.963258948910423

#Exemplo acesso de sistema

In [ ]:
import pandas as pd

In [ ]:
pd = pd.read_csv("acessos_sistema.csv")

In [ ]:
df

     valor  frequencia  tempo_entre_compras    categoria
0   169.87          13                  9.1    vestuario
1   144.47          18                  8.1  eletronicos
2   175.91           9                  9.7  alimentacao
3   210.92           5                 12.1  eletronicos
4   140.63           7                  6.4  alimentacao
..     ...         ...                  ...          ...
95  724.38           1                 32.2  alimentacao
96  935.53           2                 35.2  eletronicos
97  931.33           2                 26.9  eletronicos
98  900.61           1                 27.8  eletronicos
99  871.85           1                 21.7  eletronicos

[100 rows x 4 columns]

In [ ]:
(df.head())

    valor  frequencia  tempo_entre_compras    categoria
0  169.87          13                  9.1    vestuario
1  144.47          18                  8.1  eletronicos
2  175.91           9                  9.7  alimentacao
3  210.92           5                 12.1  eletronicos
4  140.63           7                  6.4  alimentacao

In [ ]:
(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   valor                100 non-null    float64
 1   frequencia           100 non-null    int64
 2   tempo_entre_compras  100 non-null    float64
 3   categoria            100 non-null    object
dtypes: float64(2), int64(1), object(1)
memory usage: 3.3+ KB

In [ ]:
(df.corr(numeric_only=True))

                        valor  frequencia  tempo_entre_compras
valor                1.000000   -0.530260             0.941256
frequencia          -0.530260    1.000000            -0.552453
tempo_entre_compras  0.941256   -0.552453             1.000000

In [ ]:
(df.describe())

             valor  frequencia  tempo_entre_compras
count   100.000000  100.000000            100.00000
mean    219.652400    9.820000              9.91900
std     225.978833    4.963259              8.01444
min      45.210000    1.000000              3.40000
25%     128.042500    6.000000              6.27500
50%     153.090000   10.000000              7.55000
75%     182.885000   14.000000              9.10000
max    1016.240000   19.000000             41.90000

In [ ]:
(df.tail())

     valor  frequencia  tempo_entre_compras    categoria
95  724.38           1                 32.2  alimentacao
96  935.53           2                 35.2  eletronicos
97  931.33           2                 26.9  eletronicos
98  900.61           1                 27.8  eletronicos
99  871.85           1                 21.7  eletronicos

In [ ]:
(df.value_counts())

valor    frequencia  tempo_entre_compras  categoria
45.21    7           4.7                  alimentacao    1
70.50    8           5.9                  alimentacao    1
71.61    5           6.9                  alimentacao    1
73.47    8           8.7                  alimentacao    1
79.48    15          6.0                  eletronicos    1
                                                        ..
900.61   1           27.8                 eletronicos    1
911.65   2           41.9                 eletronicos    1
931.33   2           26.9                 eletronicos    1
935.53   2           35.2                 eletronicos    1
1016.24  1           39.2                 vestuario      1
Name: count, Length: 100, dtype: int64

# Exemplo de nba

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("nba.csv")

In [ ]:
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df.describe())

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [ ]:
(df.tail())

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.corr(numeric_only=True)

          Number       Age    Weight    Salary
Number  1.000000  0.028724  0.206921 -0.112386
Age     0.028724  1.000000  0.087183  0.213459
Weight  0.206921  0.087183  1.000000  0.138321
Salary -0.112386  0.213459  0.138321  1.000000

In [ ]:
df.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
(df.value_counts())

Name            Team                    Number  Position  Age   Height  Weight  College         Salary
Zach Randolph   Memphis Grizzlies       50.0    PF        34.0  6-9     260.0   Michigan State  9638555.0     1
Aaron Brooks    Chicago Bulls           0.0     PG        31.0  6-0     161.0   Oregon          2250000.0     1
Aaron Gordon    Orlando Magic           0.0     PF        20.0  6-9     220.0   Arizona         4171680.0     1
Aaron Harrison  Charlotte Hornets       9.0     SG        21.0  6-6     210.0   Kentucky        525093.0      1
Adreian Payne   Minnesota Timberwolves  33.0    PF        25.0  6-10    237.0   Michigan State  1938840.0     1
                                                                                                             ..
Andrew Bogut    Golden State Warriors   12.0    C         31.0  7-0     260.0   Utah            13800000.0    1
Andre Roberson  Oklahoma City Thunder   21.0    SG        24.0  6-7     210.0   Colorado        1210800.0     1
Andre Miller    San Antonio Spurs       24.0    PG        40.0  6-3     200.0   Utah            250750.0      1
Andre Iguodala  Golden State Warriors   9.0     SF        32.0  6-6     215.0   Arizona         11710456.0    1
Andre Drummond  Detroit Pistons         0.0     C         22.0  6-11    279.0   Connecticut     3272091.0     1
Name: count, Length: 364, dtype: int64

In [ ]:
df['Age'].mean()
df['Age'].max()
df['Age'].median()
df['Age'].tail()
df['Age'].sum()

np.float64(12311.0)

# Exemplo heart

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("heart.csv")

In [ ]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
print(df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]

In [ ]:
(df.tail())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [ ]:
df.corr()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.098447,-0.068653,0.279351,0.213678,0.121308,-0.116211,-0.398522,0.096801,0.210013,-0.168814,0.276326,0.068001,-0.225439
sex,-0.098447,1.000000,-0.049353,-0.056769,-0.197912,0.045032,-0.058196,-0.044020,0.141664,0.096093,-0.030711,0.118261,0.210041,-0.280937
cp,-0.068653,-0.049353,1.000000,0.047608,-0.076904,0.094444,0.044421,0.295762,-0.394280,-0.149230,0.119717,-0.181053,-0.161736,0.433798
trestbps,0.279351,-0.056769,0.047608,1.000000,0.123174,0.177531,-0.114103,-0.046698,0.067616,0.193216,-0.121475,0.101389,0.062210,-0.144931
chol,0.213678,-0.197912,-0.076904,0.123174,1.000000,0.013294,-0.151040,-0.009940,0.067023,0.053952,-0.004038,0.070511,0.098803,-0.085239
fbs,0.121308,0.045032,0.094444,0.177531,0.013294,1.000000,-0.084189,-0.008567,0.025665,0.005747,-0.059894,0.137979,-0.032019,-0.028046
restecg,-0.116211,-0.058196,0.044421,-0.114103,-0.151040,-0.084189,1.000000,0.044123,-0.070733,-0.058770,0.093045,-0.072042,-0.011981,0.137230
thalach,-0.398522,-0.044020,0.295762,-0.046698,-0.009940,-0.008567,0.044123,1.000000,-0.378812,-0.344187,0.386784,-0.213177,-0.096439,0.421741
exang,0.096801,0.141664,-0.394280,0.067616,0.067023,0.025665,-0.070733,-0.378812,1.000000,0.288223,-0.257748,0.115739,0.206754,-0.436757
oldpeak,0.210013,0.096093,-0.149230,0.193216,0.053952,0.005747,-0.058770,-0.344187,0.288223,1.000000,-0.577537,0.222682,0.210244,-0.430696
slope,-0.168814,-0.030711,0.119717,-0.121475,-0.004038,-0.059894,0.093045,0.386784,-0.257748,-0.577537,1.000000,-0.080155,-0.104764,0.345877
ca,0.276326,0.118261,-0.181053,0.101389,0.070511,0.137979,-0.072042,-0.213177,0.115739,0.222682,-0.080155,1.000000,0.151832,-0.391724
thal,0.068001,0.210041,-0.161736,0.062210,0.098803,-0.032019,-0.011981,-0.096439,0.206754,0.210244,-0.104764,0.151832,1.000000,-0.344029
target,-0.225439,-0.280937,0.433798,-0.144931,-0.085239,-0.028046,0.137230,0.421741,-0.436757,-0.430696,0.345877,-0.391724,-0.344029,1.000000

In [ ]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
df.value_counts()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
38   1    2   138       175   0    1        173      0      0.0      2      4   2     1         2
59   1    2   126       218   1    1        134      0      2.2      1      1   1     0         1
          1   140       221   0    1        164      1      0.0      2      0   2     1         1
          0   170       326   0    0        140      1      3.4      0      0   3     0         1
              164       176   1    0        90       0      1.0      1      2   1     0         1
                                                                                               ..
51   1    0   140       261   0    0        186      1      0.0      2      0   2     1         1
     0    2   140       308   0    0        142      0      1.5      2      1   2     1         1
              130       256   0    0        149      0      0.5      2      0   2     1         1
              120       295   0    0        157      0      0.6      2      0   2     1         1
     1    2   125       245   1    0        166      0      2.4      1      0   2     1         1
Name: count, Length: 302, dtype: int64

# Exemplo de titanic

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("titanic.csv")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200