#exemplo da combinacao da funcao matematica

###dado do numero qualquer

In [1]:
import pandas as pd

df = pd.DataFrame({
    1 : [102,233,344,456,567,654,781,891,912],
    2 : [244,456,655,892,1023,1245,1453,1623,1892],
    3 : [395,636,925,1245,1562,1892,2134,2456,2780],
    4 : [496,845,1255,1623,2099,2499,2899,3245,3652],
    5 : [543,1055,1565,2091,2556,3092,3546,4094,4567],
    6 : [623,1245,1843,2445,3034,3672,4245,4892,5431],
    7 : [712,1431,2134,2834,3543,4231,4902,5678,6345],
    8 : [812,1672,2499,3202,4024,4892,5678,6452,7812],
    9 : [912,1892,2781,3645,4567,5431,6345,7823,8120],
    10: [1432,2344,3092,4092,5092,6782,7890,8234,9234],
    11 : [1191,2271,3389,4461,5565,6676,7779,8867,9999],
    12 : [1223,2445,3654,4856,6067,7298,8443,9634,10834]
    })

In [2]:
print(df)

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

###funcao todo individual

In [3]:
print(df.median())

1      567.0
2     1023.0
3     1562.0
4     2099.0
5     2556.0
6     3034.0
7     3543.0
8     4024.0
9     4567.0
10    5092.0
11    5565.0
12    6067.0
dtype: float64

In [4]:
print(df.count())

1     9
2     9
3     9
4     9
5     9
6     9
7     9
8     9
9     9
10    9
11    9
12    9
dtype: int64

In [5]:
print(df.idxmax())

1     8
2     8
3     8
4     8
5     8
6     8
7     8
8     8
9     8
10    8
11    8
12    8
dtype: int64

In [6]:
print(df.idxmin())

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [7]:
print(df.sum())

1      4940
2      9483
3     14025
4     18613
5     23109
6     27430
7     31810
8     37043
9     41516
10    48192
11    50198
12    54454
dtype: int64

In [8]:
(df.corr())

,1,2,3,4,5,6,7,8,9,10,11,12
1,1.000000,0.992450,0.993630,0.995417,0.995956,0.996303,0.995814,0.987721,0.996437,0.990939,0.995389,0.995885
2,0.992450,1.000000,0.998354,0.997936,0.998936,0.998657,0.998795,0.998580,0.994693,0.992778,0.999023,0.998910
3,0.993630,0.998354,1.000000,0.999515,0.999448,0.999401,0.999456,0.997743,0.996565,0.994695,0.999547,0.999512
4,0.995417,0.997936,0.999515,1.000000,0.999351,0.999495,0.999428,0.997009,0.996449,0.995950,0.999641,0.999654
5,0.995956,0.998936,0.999448,0.999351,1.000000,0.999952,0.999939,0.997372,0.997768,0.994050,0.999874,0.999929
6,0.996303,0.998657,0.999401,0.999495,0.999952,1.000000,0.999941,0.997171,0.998036,0.994597,0.999896,0.999933
7,0.995814,0.998795,0.999456,0.999428,0.999939,0.999941,1.000000,0.997619,0.997962,0.993708,0.999926,0.999925
8,0.987721,0.998580,0.997743,0.997009,0.997372,0.997171,0.997619,1.000000,0.992860,0.990770,0.997958,0.997584
9,0.996437,0.994693,0.996565,0.996449,0.997768,0.998036,0.997962,0.992860,1.000000,0.989908,0.997357,0.997327
10,0.990939,0.992778,0.994695,0.995950,0.994050,0.994597,0.993708,0.990770,0.989908,1.000000,0.994575,0.994647
11,0.995389,0.999023,0.999547,0.999641,0.999874,0.999896,0.999926,0.997958,0.997357,0.994575,1.000000,0.999957
12,0.995885,0.998910,0.999512,0.999654,0.999929,0.999933,0.999925,0.997584,0.997327,0.994647,0.999957,1.000000

In [9]:
(df.describe())

,1,2,3,4,5,6,7,8,9,10,11,12
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,548.888889,1053.666667,1558.333333,2068.111111,2567.666667,3047.777778,3534.444444,4115.888889,4612.888889,5354.666667,5577.555556,6050.444444
std,288.150327,550.204053,824.950453,1095.306743,1377.461978,1652.591660,1926.527388,2305.087658,2541.375191,2807.120233,3013.186897,3287.825235
min,102.000000,244.000000,395.000000,496.000000,543.000000,623.000000,712.000000,812.000000,912.000000,1432.000000,1191.000000,1223.000000
25%,344.000000,655.000000,925.000000,1255.000000,1565.000000,1843.000000,2134.000000,2499.000000,2781.000000,3092.000000,3389.000000,3654.000000
50%,567.000000,1023.000000,1562.000000,2099.000000,2556.000000,3034.000000,3543.000000,4024.000000,4567.000000,5092.000000,5565.000000,6067.000000
75%,781.000000,1453.000000,2134.000000,2899.000000,3546.000000,4245.000000,4902.000000,5678.000000,6345.000000,7890.000000,7779.000000,8443.000000
max,912.000000,1892.000000,2780.000000,3652.000000,4567.000000,5431.000000,6345.000000,7812.000000,8120.000000,9234.000000,9999.000000,10834.000000

In [10]:
print(df.value_counts())

1    2     3     4     5     6     7     8     9     10    11    12
102  244   395   496   543   623   712   812   912   1432  1191  1223     1
233  456   636   845   1055  1245  1431  1672  1892  2344  2271  2445     1
344  655   925   1255  1565  1843  2134  2499  2781  3092  3389  3654     1
456  892   1245  1623  2091  2445  2834  3202  3645  4092  4461  4856     1
567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565  6067     1
654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676  7298     1
781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779  8443     1
891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867  9634     1
912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834    1
Name: count, dtype: int64

In [11]:
df.values

array([[  102,   244,   395,   496,   543,   623,   712,   812,   912,
         1432,  1191,  1223],
       [  233,   456,   636,   845,  1055,  1245,  1431,  1672,  1892,
         2344,  2271,  2445],
       [  344,   655,   925,  1255,  1565,  1843,  2134,  2499,  2781,
         3092,  3389,  3654],
       [  456,   892,  1245,  1623,  2091,  2445,  2834,  3202,  3645,
         4092,  4461,  4856],
       [  567,  1023,  1562,  2099,  2556,  3034,  3543,  4024,  4567,
         5092,  5565,  6067],
       [  654,  1245,  1892,  2499,  3092,  3672,  4231,  4892,  5431,
         6782,  6676,  7298],
       [  781,  1453,  2134,  2899,  3546,  4245,  4902,  5678,  6345,
         7890,  7779,  8443],
       [  891,  1623,  2456,  3245,  4094,  4892,  5678,  6452,  7823,
         8234,  8867,  9634],
       [  912,  1892,  2780,  3652,  4567,  5431,  6345,  7812,  8120,
         9234,  9999, 10834]])

In [12]:
print(df.max())

1       912
2      1892
3      2780
4      3652
5      4567
6      5431
7      6345
8      7812
9      8120
10     9234
11     9999
12    10834
dtype: int64

In [13]:
print(df.min())

1      102
2      244
3      395
4      496
5      543
6      623
7      712
8      812
9      912
10    1432
11    1191
12    1223
dtype: int64

In [14]:
print(df.tail())

    1     2     3     4     5     6     7     8     9     10    11     12
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [15]:
print(df.std())

1      288.150327
2      550.204053
3      824.950453
4     1095.306743
5     1377.461978
6     1652.591660
7     1926.527388
8     2305.087658
9     2541.375191
10    2807.120233
11    3013.186897
12    3287.825235
dtype: float64

In [16]:
print(df.mode())

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [17]:
print(df.nunique())

1     9
2     9
3     9
4     9
5     9
6     9
7     9
8     9
9     9
10    9
11    9
12    9
dtype: int64

In [18]:
print(df.var())

1     8.303061e+04
2     3.027245e+05
3     6.805432e+05
4     1.199697e+06
5     1.897401e+06
6     2.731059e+06
7     3.711508e+06
8     5.313429e+06
9     6.458588e+06
10    7.879924e+06
11    9.079295e+06
12    1.080979e+07
dtype: float64

In [19]:
print(df.round())

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

###df.median() com toda funcao matematica

In [20]:
print(df.median() + df.median())

1      1134.0
2      2046.0
3      3124.0
4      4198.0
5      5112.0
6      6068.0
7      7086.0
8      8048.0
9      9134.0
10    10184.0
11    11130.0
12    12134.0
dtype: float64

In [21]:
print(df.median() + df.count())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [22]:
print(df.median() + df.std())

1      855.150327
2     1573.204053
3     2386.950453
4     3194.306743
5     3933.461978
6     4686.591660
7     5469.527388
8     6329.087658
9     7108.375191
10    7899.120233
11    8578.186897
12    9354.825235
dtype: float64

In [23]:
(df.median() + df.mode())

,1,2,3,4,5,6,7,8,9,10,11,12
0,669.0,1267.0,1957.0,2595.0,3099.0,3657.0,4255.0,4836.0,5479.0,6524.0,6756.0,7290.0
1,800.0,1479.0,2198.0,2944.0,3611.0,4279.0,4974.0,5696.0,6459.0,7436.0,7836.0,8512.0
2,911.0,1678.0,2487.0,3354.0,4121.0,4877.0,5677.0,6523.0,7348.0,8184.0,8954.0,9721.0
3,1023.0,1915.0,2807.0,3722.0,4647.0,5479.0,6377.0,7226.0,8212.0,9184.0,10026.0,10923.0
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

In [24]:
print(df.median() + df.idxmax())

1      575.0
2     1031.0
3     1570.0
4     2107.0
5     2564.0
6     3042.0
7     3551.0
8     4032.0
9     4575.0
10    5100.0
11    5573.0
12    6075.0
dtype: float64

In [25]:
print(df.median() + df.idxmin())

1      567.0
2     1023.0
3     1562.0
4     2099.0
5     2556.0
6     3034.0
7     3543.0
8     4024.0
9     4567.0
10    5092.0
11    5565.0
12    6067.0
dtype: float64

In [26]:
print(df.median() + df.sum())

1      5507.0
2     10506.0
3     15587.0
4     20712.0
5     25665.0
6     30464.0
7     35353.0
8     41067.0
9     46083.0
10    53284.0
11    55763.0
12    60521.0
dtype: float64

In [27]:
(df.median() + df.corr())

,1,2,3,4,5,6,7,8,9,10,11,12
1,568.000000,1023.992450,1562.993630,2099.995417,2556.995956,3034.996303,3543.995814,4024.987721,4567.996437,5092.990939,5565.995389,6067.995885
2,567.992450,1024.000000,1562.998354,2099.997936,2556.998936,3034.998657,3543.998795,4024.998580,4567.994693,5092.992778,5565.999023,6067.998910
3,567.993630,1023.998354,1563.000000,2099.999515,2556.999448,3034.999401,3543.999456,4024.997743,4567.996565,5092.994695,5565.999547,6067.999512
4,567.995417,1023.997936,1562.999515,2100.000000,2556.999351,3034.999495,3543.999428,4024.997009,4567.996449,5092.995950,5565.999641,6067.999654
5,567.995956,1023.998936,1562.999448,2099.999351,2557.000000,3034.999952,3543.999939,4024.997372,4567.997768,5092.994050,5565.999874,6067.999929
6,567.996303,1023.998657,1562.999401,2099.999495,2556.999952,3035.000000,3543.999941,4024.997171,4567.998036,5092.994597,5565.999896,6067.999933
7,567.995814,1023.998795,1562.999456,2099.999428,2556.999939,3034.999941,3544.000000,4024.997619,4567.997962,5092.993708,5565.999926,6067.999925
8,567.987721,1023.998580,1562.997743,2099.997009,2556.997372,3034.997171,3543.997619,4025.000000,4567.992860,5092.990770,5565.997958,6067.997584
9,567.996437,1023.994693,1562.996565,2099.996449,2556.997768,3034.998036,3543.997962,4024.992860,4568.000000,5092.989908,5565.997357,6067.997327
10,567.990939,1023.992778,1562.994695,2099.995950,2556.994050,3034.994597,3543.993708,4024.990770,4567.989908,5093.000000,5565.994575,6067.994647
11,567.995389,1023.999023,1562.999547,2099.999641,2556.999874,3034.999896,3543.999926,4024.997958,4567.997357,5092.994575,5566.000000,6067.999957
12,567.995885,1023.998910,1562.999512,2099.999654,2556.999929,3034.999933,3543.999925,4024.997584,4567.997327,5092.994647,5565.999957,6068.000000

In [28]:
(df.median() + df.describe())

,1,2,3,4,5,6,7,8,9,10,11,12
count,576.000000,1032.000000,1571.000000,2108.000000,2565.000000,3043.000000,3552.000000,4033.000000,4576.000000,5101.000000,5574.000000,6076.000000
mean,1115.888889,2076.666667,3120.333333,4167.111111,5123.666667,6081.777778,7077.444444,8139.888889,9179.888889,10446.666667,11142.555556,12117.444444
std,855.150327,1573.204053,2386.950453,3194.306743,3933.461978,4686.591660,5469.527388,6329.087658,7108.375191,7899.120233,8578.186897,9354.825235
min,669.000000,1267.000000,1957.000000,2595.000000,3099.000000,3657.000000,4255.000000,4836.000000,5479.000000,6524.000000,6756.000000,7290.000000
25%,911.000000,1678.000000,2487.000000,3354.000000,4121.000000,4877.000000,5677.000000,6523.000000,7348.000000,8184.000000,8954.000000,9721.000000
50%,1134.000000,2046.000000,3124.000000,4198.000000,5112.000000,6068.000000,7086.000000,8048.000000,9134.000000,10184.000000,11130.000000,12134.000000
75%,1348.000000,2476.000000,3696.000000,4998.000000,6102.000000,7279.000000,8445.000000,9702.000000,10912.000000,12982.000000,13344.000000,14510.000000
max,1479.000000,2915.000000,4342.000000,5751.000000,7123.000000,8465.000000,9888.000000,11836.000000,12687.000000,14326.000000,15564.000000,16901.000000

In [29]:
print(df.median() + df.min())

1      669.0
2     1267.0
3     1957.0
4     2595.0
5     3099.0
6     3657.0
7     4255.0
8     4836.0
9     5479.0
10    6524.0
11    6756.0
12    7290.0
dtype: float64

In [30]:
print(df.median() + df.max())

1      1479.0
2      2915.0
3      4342.0
4      5751.0
5      7123.0
6      8465.0
7      9888.0
8     11836.0
9     12687.0
10    14326.0
11    15564.0
12    16901.0
dtype: float64

In [31]:
(df.median() + df.tail())

,1,2,3,4,5,6,7,8,9,10,11,12
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

In [32]:
print(df.median() + df.count())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [33]:
(df.median() + df.abs())

,1,2,3,4,5,6,7,8,9,10,11,12
0,669.0,1267.0,1957.0,2595.0,3099.0,3657.0,4255.0,4836.0,5479.0,6524.0,6756.0,7290.0
1,800.0,1479.0,2198.0,2944.0,3611.0,4279.0,4974.0,5696.0,6459.0,7436.0,7836.0,8512.0
2,911.0,1678.0,2487.0,3354.0,4121.0,4877.0,5677.0,6523.0,7348.0,8184.0,8954.0,9721.0
3,1023.0,1915.0,2807.0,3722.0,4647.0,5479.0,6377.0,7226.0,8212.0,9184.0,10026.0,10923.0
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

In [34]:
(df.median() + df.mode())

,1,2,3,4,5,6,7,8,9,10,11,12
0,669.0,1267.0,1957.0,2595.0,3099.0,3657.0,4255.0,4836.0,5479.0,6524.0,6756.0,7290.0
1,800.0,1479.0,2198.0,2944.0,3611.0,4279.0,4974.0,5696.0,6459.0,7436.0,7836.0,8512.0
2,911.0,1678.0,2487.0,3354.0,4121.0,4877.0,5677.0,6523.0,7348.0,8184.0,8954.0,9721.0
3,1023.0,1915.0,2807.0,3722.0,4647.0,5479.0,6377.0,7226.0,8212.0,9184.0,10026.0,10923.0
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

In [35]:
print(df.median() + df.nunique())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [36]:
print(df.median() + df.var())

1     8.359761e+04
2     3.037475e+05
3     6.821052e+05
4     1.201796e+06
5     1.899957e+06
6     2.734093e+06
7     3.715051e+06
8     5.317453e+06
9     6.463155e+06
10    7.885016e+06
11    9.084860e+06
12    1.081586e+07
dtype: float64

In [37]:
print(df)

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [38]:
(df.median() + df.round())

,1,2,3,4,5,6,7,8,9,10,11,12
0,669.0,1267.0,1957.0,2595.0,3099.0,3657.0,4255.0,4836.0,5479.0,6524.0,6756.0,7290.0
1,800.0,1479.0,2198.0,2944.0,3611.0,4279.0,4974.0,5696.0,6459.0,7436.0,7836.0,8512.0
2,911.0,1678.0,2487.0,3354.0,4121.0,4877.0,5677.0,6523.0,7348.0,8184.0,8954.0,9721.0
3,1023.0,1915.0,2807.0,3722.0,4647.0,5479.0,6377.0,7226.0,8212.0,9184.0,10026.0,10923.0
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

###df.count com todas as funcoes matematica

In [39]:
print(df.count() + df.median())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [40]:
print(df.count() + df.count())

1     18
2     18
3     18
4     18
5     18
6     18
7     18
8     18
9     18
10    18
11    18
12    18
dtype: int64

In [41]:
print(df.count() + df.idxmax())

1     17
2     17
3     17
4     17
5     17
6     17
7     17
8     17
9     17
10    17
11    17
12    17
dtype: int64

In [42]:
print(df.count() + df.idxmin())

1     9
2     9
3     9
4     9
5     9
6     9
7     9
8     9
9     9
10    9
11    9
12    9
dtype: int64

In [43]:
print(df.count() + df.sum())

1      4949
2      9492
3     14034
4     18622
5     23118
6     27439
7     31819
8     37052
9     41525
10    48201
11    50207
12    54463
dtype: int64

In [44]:
(df.count() + df.corr())

,1,2,3,4,5,6,7,8,9,10,11,12
1,10.000000,9.992450,9.993630,9.995417,9.995956,9.996303,9.995814,9.987721,9.996437,9.990939,9.995389,9.995885
2,9.992450,10.000000,9.998354,9.997936,9.998936,9.998657,9.998795,9.998580,9.994693,9.992778,9.999023,9.998910
3,9.993630,9.998354,10.000000,9.999515,9.999448,9.999401,9.999456,9.997743,9.996565,9.994695,9.999547,9.999512
4,9.995417,9.997936,9.999515,10.000000,9.999351,9.999495,9.999428,9.997009,9.996449,9.995950,9.999641,9.999654
5,9.995956,9.998936,9.999448,9.999351,10.000000,9.999952,9.999939,9.997372,9.997768,9.994050,9.999874,9.999929
6,9.996303,9.998657,9.999401,9.999495,9.999952,10.000000,9.999941,9.997171,9.998036,9.994597,9.999896,9.999933
7,9.995814,9.998795,9.999456,9.999428,9.999939,9.999941,10.000000,9.997619,9.997962,9.993708,9.999926,9.999925
8,9.987721,9.998580,9.997743,9.997009,9.997372,9.997171,9.997619,10.000000,9.992860,9.990770,9.997958,9.997584
9,9.996437,9.994693,9.996565,9.996449,9.997768,9.998036,9.997962,9.992860,10.000000,9.989908,9.997357,9.997327
10,9.990939,9.992778,9.994695,9.995950,9.994050,9.994597,9.993708,9.990770,9.989908,10.000000,9.994575,9.994647
11,9.995389,9.999023,9.999547,9.999641,9.999874,9.999896,9.999926,9.997958,9.997357,9.994575,10.000000,9.999957
12,9.995885,9.998910,9.999512,9.999654,9.999929,9.999933,9.999925,9.997584,9.997327,9.994647,9.999957,10.000000

In [45]:
(df.count() + df.describe())

,1,2,3,4,5,6,7,8,9,10,11,12
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,557.888889,1062.666667,1567.333333,2077.111111,2576.666667,3056.777778,3543.444444,4124.888889,4621.888889,5363.666667,5586.555556,6059.444444
std,297.150327,559.204053,833.950453,1104.306743,1386.461978,1661.591660,1935.527388,2314.087658,2550.375191,2816.120233,3022.186897,3296.825235
min,111.000000,253.000000,404.000000,505.000000,552.000000,632.000000,721.000000,821.000000,921.000000,1441.000000,1200.000000,1232.000000
25%,353.000000,664.000000,934.000000,1264.000000,1574.000000,1852.000000,2143.000000,2508.000000,2790.000000,3101.000000,3398.000000,3663.000000
50%,576.000000,1032.000000,1571.000000,2108.000000,2565.000000,3043.000000,3552.000000,4033.000000,4576.000000,5101.000000,5574.000000,6076.000000
75%,790.000000,1462.000000,2143.000000,2908.000000,3555.000000,4254.000000,4911.000000,5687.000000,6354.000000,7899.000000,7788.000000,8452.000000
max,921.000000,1901.000000,2789.000000,3661.000000,4576.000000,5440.000000,6354.000000,7821.000000,8129.000000,9243.000000,10008.000000,10843.000000

In [46]:
print(df.count() + df.max())

1       921
2      1901
3      2789
4      3661
5      4576
6      5440
7      6354
8      7821
9      8129
10     9243
11    10008
12    10843
dtype: int64

In [47]:
print(df.count() + df.min())

1      111
2      253
3      404
4      505
5      552
6      632
7      721
8      821
9      921
10    1441
11    1200
12    1232
dtype: int64

In [48]:
print(df.count() + df.tail())

    1     2     3     4     5     6     7     8     9     10     11     12
4  576  1032  1571  2108  2565  3043  3552  4033  4576  5101   5574   6076
5  663  1254  1901  2508  3101  3681  4240  4901  5440  6791   6685   7307
6  790  1462  2143  2908  3555  4254  4911  5687  6354  7899   7788   8452
7  900  1632  2465  3254  4103  4901  5687  6461  7832  8243   8876   9643
8  921  1901  2789  3661  4576  5440  6354  7821  8129  9243  10008  10843

In [49]:
print(df.count() + df.std())

1      297.150327
2      559.204053
3      833.950453
4     1104.306743
5     1386.461978
6     1661.591660
7     1935.527388
8     2314.087658
9     2550.375191
10    2816.120233
11    3022.186897
12    3296.825235
dtype: float64

###df.mean com a funcao dupla da matematica

In [50]:
print(df.mean() + df.median())

1      1115.888889
2      2076.666667
3      3120.333333
4      4167.111111
5      5123.666667
6      6081.777778
7      7077.444444
8      8139.888889
9      9179.888889
10    10446.666667
11    11142.555556
12    12117.444444
dtype: float64

In [51]:
(df.mean() + df.mode())

,1,2,3,4,5,6,7,8,9,10,11,12
0,650.888889,1297.666667,1953.333333,2564.111111,3110.666667,3670.777778,4246.444444,4927.888889,5524.888889,6786.666667,6768.555556,7273.444444
1,781.888889,1509.666667,2194.333333,2913.111111,3622.666667,4292.777778,4965.444444,5787.888889,6504.888889,7698.666667,7848.555556,8495.444444
2,892.888889,1708.666667,2483.333333,3323.111111,4132.666667,4890.777778,5668.444444,6614.888889,7393.888889,8446.666667,8966.555556,9704.444444
3,1004.888889,1945.666667,2803.333333,3691.111111,4658.666667,5492.777778,6368.444444,7317.888889,8257.888889,9446.666667,10038.555556,10906.444444
4,1115.888889,2076.666667,3120.333333,4167.111111,5123.666667,6081.777778,7077.444444,8139.888889,9179.888889,10446.666667,11142.555556,12117.444444
5,1202.888889,2298.666667,3450.333333,4567.111111,5659.666667,6719.777778,7765.444444,9007.888889,10043.888889,12136.666667,12253.555556,13348.444444
6,1329.888889,2506.666667,3692.333333,4967.111111,6113.666667,7292.777778,8436.444444,9793.888889,10957.888889,13244.666667,13356.555556,14493.444444
7,1439.888889,2676.666667,4014.333333,5313.111111,6661.666667,7939.777778,9212.444444,10567.888889,12435.888889,13588.666667,14444.555556,15684.444444
8,1460.888889,2945.666667,4338.333333,5720.111111,7134.666667,8478.777778,9879.444444,11927.888889,12732.888889,14588.666667,15576.555556,16884.444444

###df.count com todas as funcoes matematica

In [52]:
print(df.count() + df.median())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [53]:
print(df.count() + df.count())

1     18
2     18
3     18
4     18
5     18
6     18
7     18
8     18
9     18
10    18
11    18
12    18
dtype: int64

In [54]:
print(df.count() + df.idxmax())

1     17
2     17
3     17
4     17
5     17
6     17
7     17
8     17
9     17
10    17
11    17
12    17
dtype: int64

In [55]:
print(df.count() + df.idxmin())

1     9
2     9
3     9
4     9
5     9
6     9
7     9
8     9
9     9
10    9
11    9
12    9
dtype: int64

In [56]:
print(df.count() + df.sum())

1      4949
2      9492
3     14034
4     18622
5     23118
6     27439
7     31819
8     37052
9     41525
10    48201
11    50207
12    54463
dtype: int64

In [57]:
(df.count() + df.corr())

,1,2,3,4,5,6,7,8,9,10,11,12
1,10.000000,9.992450,9.993630,9.995417,9.995956,9.996303,9.995814,9.987721,9.996437,9.990939,9.995389,9.995885
2,9.992450,10.000000,9.998354,9.997936,9.998936,9.998657,9.998795,9.998580,9.994693,9.992778,9.999023,9.998910
3,9.993630,9.998354,10.000000,9.999515,9.999448,9.999401,9.999456,9.997743,9.996565,9.994695,9.999547,9.999512
4,9.995417,9.997936,9.999515,10.000000,9.999351,9.999495,9.999428,9.997009,9.996449,9.995950,9.999641,9.999654
5,9.995956,9.998936,9.999448,9.999351,10.000000,9.999952,9.999939,9.997372,9.997768,9.994050,9.999874,9.999929
6,9.996303,9.998657,9.999401,9.999495,9.999952,10.000000,9.999941,9.997171,9.998036,9.994597,9.999896,9.999933
7,9.995814,9.998795,9.999456,9.999428,9.999939,9.999941,10.000000,9.997619,9.997962,9.993708,9.999926,9.999925
8,9.987721,9.998580,9.997743,9.997009,9.997372,9.997171,9.997619,10.000000,9.992860,9.990770,9.997958,9.997584
9,9.996437,9.994693,9.996565,9.996449,9.997768,9.998036,9.997962,9.992860,10.000000,9.989908,9.997357,9.997327
10,9.990939,9.992778,9.994695,9.995950,9.994050,9.994597,9.993708,9.990770,9.989908,10.000000,9.994575,9.994647
11,9.995389,9.999023,9.999547,9.999641,9.999874,9.999896,9.999926,9.997958,9.997357,9.994575,10.000000,9.999957
12,9.995885,9.998910,9.999512,9.999654,9.999929,9.999933,9.999925,9.997584,9.997327,9.994647,9.999957,10.000000

In [58]:
(df.count() + df.describe())

,1,2,3,4,5,6,7,8,9,10,11,12
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,557.888889,1062.666667,1567.333333,2077.111111,2576.666667,3056.777778,3543.444444,4124.888889,4621.888889,5363.666667,5586.555556,6059.444444
std,297.150327,559.204053,833.950453,1104.306743,1386.461978,1661.591660,1935.527388,2314.087658,2550.375191,2816.120233,3022.186897,3296.825235
min,111.000000,253.000000,404.000000,505.000000,552.000000,632.000000,721.000000,821.000000,921.000000,1441.000000,1200.000000,1232.000000
25%,353.000000,664.000000,934.000000,1264.000000,1574.000000,1852.000000,2143.000000,2508.000000,2790.000000,3101.000000,3398.000000,3663.000000
50%,576.000000,1032.000000,1571.000000,2108.000000,2565.000000,3043.000000,3552.000000,4033.000000,4576.000000,5101.000000,5574.000000,6076.000000
75%,790.000000,1462.000000,2143.000000,2908.000000,3555.000000,4254.000000,4911.000000,5687.000000,6354.000000,7899.000000,7788.000000,8452.000000
max,921.000000,1901.000000,2789.000000,3661.000000,4576.000000,5440.000000,6354.000000,7821.000000,8129.000000,9243.000000,10008.000000,10843.000000

In [59]:
print(df.count() + df.max())

1       921
2      1901
3      2789
4      3661
5      4576
6      5440
7      6354
8      7821
9      8129
10     9243
11    10008
12    10843
dtype: int64

In [60]:
print(df.count() + df.min())

1      111
2      253
3      404
4      505
5      552
6      632
7      721
8      821
9      921
10    1441
11    1200
12    1232
dtype: int64

In [61]:
print(df.count() + df.tail())

    1     2     3     4     5     6     7     8     9     10     11     12
4  576  1032  1571  2108  2565  3043  3552  4033  4576  5101   5574   6076
5  663  1254  1901  2508  3101  3681  4240  4901  5440  6791   6685   7307
6  790  1462  2143  2908  3555  4254  4911  5687  6354  7899   7788   8452
7  900  1632  2465  3254  4103  4901  5687  6461  7832  8243   8876   9643
8  921  1901  2789  3661  4576  5440  6354  7821  8129  9243  10008  10843

In [62]:
print(df.count() + df.std())

1      297.150327
2      559.204053
3      833.950453
4     1104.306743
5     1386.461978
6     1661.591660
7     1935.527388
8     2314.087658
9     2550.375191
10    2816.120233
11    3022.186897
12    3296.825235
dtype: float64

###df.mode com a funcao dupla da matematica

In [63]:
print(df)

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [64]:
(df.mode() + df.median())

,1,2,3,4,5,6,7,8,9,10,11,12
0,669.0,1267.0,1957.0,2595.0,3099.0,3657.0,4255.0,4836.0,5479.0,6524.0,6756.0,7290.0
1,800.0,1479.0,2198.0,2944.0,3611.0,4279.0,4974.0,5696.0,6459.0,7436.0,7836.0,8512.0
2,911.0,1678.0,2487.0,3354.0,4121.0,4877.0,5677.0,6523.0,7348.0,8184.0,8954.0,9721.0
3,1023.0,1915.0,2807.0,3722.0,4647.0,5479.0,6377.0,7226.0,8212.0,9184.0,10026.0,10923.0
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1221.0,2268.0,3454.0,4598.0,5648.0,6706.0,7774.0,8916.0,9998.0,11874.0,12241.0,13365.0
6,1348.0,2476.0,3696.0,4998.0,6102.0,7279.0,8445.0,9702.0,10912.0,12982.0,13344.0,14510.0
7,1458.0,2646.0,4018.0,5344.0,6650.0,7926.0,9221.0,10476.0,12390.0,13326.0,14432.0,15701.0
8,1479.0,2915.0,4342.0,5751.0,7123.0,8465.0,9888.0,11836.0,12687.0,14326.0,15564.0,16901.0

In [65]:
print(df.mode() + df.count())

    1     2     3     4     5     6     7     8     9     10     11     12
0  111   253   404   505   552   632   721   821   921  1441   1200   1232
1  242   465   645   854  1064  1254  1440  1681  1901  2353   2280   2454
2  353   664   934  1264  1574  1852  2143  2508  2790  3101   3398   3663
3  465   901  1254  1632  2100  2454  2843  3211  3654  4101   4470   4865
4  576  1032  1571  2108  2565  3043  3552  4033  4576  5101   5574   6076
5  663  1254  1901  2508  3101  3681  4240  4901  5440  6791   6685   7307
6  790  1462  2143  2908  3555  4254  4911  5687  6354  7899   7788   8452
7  900  1632  2465  3254  4103  4901  5687  6461  7832  8243   8876   9643
8  921  1901  2789  3661  4576  5440  6354  7821  8129  9243  10008  10843

In [66]:
print(df.mode() + df.idxmax())

    1     2     3     4     5     6     7     8     9     10     11     12
0  110   252   403   504   551   631   720   820   920  1440   1199   1231
1  241   464   644   853  1063  1253  1439  1680  1900  2352   2279   2453
2  352   663   933  1263  1573  1851  2142  2507  2789  3100   3397   3662
3  464   900  1253  1631  2099  2453  2842  3210  3653  4100   4469   4864
4  575  1031  1570  2107  2564  3042  3551  4032  4575  5100   5573   6075
5  662  1253  1900  2507  3100  3680  4239  4900  5439  6790   6684   7306
6  789  1461  2142  2907  3554  4253  4910  5686  6353  7898   7787   8451
7  899  1631  2464  3253  4102  4900  5686  6460  7831  8242   8875   9642
8  920  1900  2788  3660  4575  5439  6353  7820  8128  9242  10007  10842

In [67]:
print(df.mode() + df.idxmin())

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [68]:
print(df.mode() + df.sum())

     1      2      3      4      5      6      7      8      9      10     11  \
0  5042   9727  14420  19109  23652  28053  32522  37855  42428  49624  51389
1  5173   9939  14661  19458  24164  28675  33241  38715  43408  50536  52469
2  5284  10138  14950  19868  24674  29273  33944  39542  44297  51284  53587
3  5396  10375  15270  20236  25200  29875  34644  40245  45161  52284  54659
4  5507  10506  15587  20712  25665  30464  35353  41067  46083  53284  55763
5  5594  10728  15917  21112  26201  31102  36041  41935  46947  54974  56874
6  5721  10936  16159  21512  26655  31675  36712  42721  47861  56082  57977
7  5831  11106  16481  21858  27203  32322  37488  43495  49339  56426  59065
8  5852  11375  16805  22265  27676  32861  38155  44855  49636  57426  60197

      12
0  55677
1  56899
2  58108
3  59310
4  60521
5  61752
6  62897
7  64088
8  65288

In [69]:
(df.mode() + df.corr())

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,234.000000,456.992450,636.993630,845.995417,1055.995956,1245.996303,1431.995814,1672.987721,1892.996437,2344.990939,2271.995389,2445.995885
2,344.992450,656.000000,925.998354,1255.997936,1565.998936,1843.998657,2134.998795,2499.998580,2781.994693,3092.992778,3389.999023,3654.998910
3,456.993630,892.998354,1246.000000,1623.999515,2091.999448,2445.999401,2834.999456,3202.997743,3645.996565,4092.994695,4461.999547,4856.999512
4,567.995417,1023.997936,1562.999515,2100.000000,2556.999351,3034.999495,3543.999428,4024.997009,4567.996449,5092.995950,5565.999641,6067.999654
5,654.995956,1245.998936,1892.999448,2499.999351,3093.000000,3672.999952,4231.999939,4892.997372,5431.997768,6782.994050,6676.999874,7298.999929
6,781.996303,1453.998657,2134.999401,2899.999495,3546.999952,4246.000000,4902.999941,5678.997171,6345.998036,7890.994597,7779.999896,8443.999933
7,891.995814,1623.998795,2456.999456,3245.999428,4094.999939,4892.999941,5679.000000,6452.997619,7823.997962,8234.993708,8867.999926,9634.999925
8,912.987721,1892.998580,2780.997743,3652.997009,4567.997372,5431.997171,6345.997619,7813.000000,8120.992860,9234.990770,9999.997958,10834.997584
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
print(df.mode() + df.describe())

       1   2   3   4   5   6   7   8   9   10  11  12
0     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
5     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
6     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
7     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
8     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
25%   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
50%   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
75%   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
count NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
max   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
mean  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
min   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
std   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [71]:
print(df.mode() + df.min())

     1     2     3     4     5     6     7     8     9      10     11     12
0   204   488   790   992  1086  1246  1424  1624  1824   2864   2382   2446
1   335   700  1031  1341  1598  1868  2143  2484  2804   3776   3462   3668
2   446   899  1320  1751  2108  2466  2846  3311  3693   4524   4580   4877
3   558  1136  1640  2119  2634  3068  3546  4014  4557   5524   5652   6079
4   669  1267  1957  2595  3099  3657  4255  4836  5479   6524   6756   7290
5   756  1489  2287  2995  3635  4295  4943  5704  6343   8214   7867   8521
6   883  1697  2529  3395  4089  4868  5614  6490  7257   9322   8970   9666
7   993  1867  2851  3741  4637  5515  6390  7264  8735   9666  10058  10857
8  1014  2136  3175  4148  5110  6054  7057  8624  9032  10666  11190  12057

In [72]:
(df.mode() + df.max())

,1,2,3,4,5,6,7,8,9,10,11,12
0,1014,2136,3175,4148,5110,6054,7057,8624,9032,10666,11190,12057
1,1145,2348,3416,4497,5622,6676,7776,9484,10012,11578,12270,13279
2,1256,2547,3705,4907,6132,7274,8479,10311,10901,12326,13388,14488
3,1368,2784,4025,5275,6658,7876,9179,11014,11765,13326,14460,15690
4,1479,2915,4342,5751,7123,8465,9888,11836,12687,14326,15564,16901
5,1566,3137,4672,6151,7659,9103,10576,12704,13551,16016,16675,18132
6,1693,3345,4914,6551,8113,9676,11247,13490,14465,17124,17778,19277
7,1803,3515,5236,6897,8661,10323,12023,14264,15943,17468,18866,20468
8,1824,3784,5560,7304,9134,10862,12690,15624,16240,18468,19998,21668

In [73]:
(df.mode() + df.tail())

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1134.0,2046.0,3124.0,4198.0,5112.0,6068.0,7086.0,8048.0,9134.0,10184.0,11130.0,12134.0
5,1308.0,2490.0,3784.0,4998.0,6184.0,7344.0,8462.0,9784.0,10862.0,13564.0,13352.0,14596.0
6,1562.0,2906.0,4268.0,5798.0,7092.0,8490.0,9804.0,11356.0,12690.0,15780.0,15558.0,16886.0
7,1782.0,3246.0,4912.0,6490.0,8188.0,9784.0,11356.0,12904.0,15646.0,16468.0,17734.0,19268.0
8,1824.0,3784.0,5560.0,7304.0,9134.0,10862.0,12690.0,15624.0,16240.0,18468.0,19998.0,21668.0

In [74]:
(df.mode() + df.std())

,1,2,3,4,5,6,7,8,9,10,11,12
0,390.150327,794.204053,1219.950453,1591.306743,1920.461978,2275.59166,2638.527388,3117.087658,3453.375191,4239.120233,4204.186897,4510.825235
1,521.150327,1006.204053,1460.950453,1940.306743,2432.461978,2897.59166,3357.527388,3977.087658,4433.375191,5151.120233,5284.186897,5732.825235
2,632.150327,1205.204053,1749.950453,2350.306743,2942.461978,3495.59166,4060.527388,4804.087658,5322.375191,5899.120233,6402.186897,6941.825235
3,744.150327,1442.204053,2069.950453,2718.306743,3468.461978,4097.59166,4760.527388,5507.087658,6186.375191,6899.120233,7474.186897,8143.825235
4,855.150327,1573.204053,2386.950453,3194.306743,3933.461978,4686.59166,5469.527388,6329.087658,7108.375191,7899.120233,8578.186897,9354.825235
5,942.150327,1795.204053,2716.950453,3594.306743,4469.461978,5324.59166,6157.527388,7197.087658,7972.375191,9589.120233,9689.186897,10585.825235
6,1069.150327,2003.204053,2958.950453,3994.306743,4923.461978,5897.59166,6828.527388,7983.087658,8886.375191,10697.120233,10792.186897,11730.825235
7,1179.150327,2173.204053,3280.950453,4340.306743,5471.461978,6544.59166,7604.527388,8757.087658,10364.375191,11041.120233,11880.186897,12921.825235
8,1200.150327,2442.204053,3604.950453,4747.306743,5944.461978,7083.59166,8271.527388,10117.087658,10661.375191,12041.120233,13012.186897,14121.825235

In [75]:
(df.mode() + df.mode())

,1,2,3,4,5,6,7,8,9,10,11,12
0,204,488,790,992,1086,1246,1424,1624,1824,2864,2382,2446
1,466,912,1272,1690,2110,2490,2862,3344,3784,4688,4542,4890
2,688,1310,1850,2510,3130,3686,4268,4998,5562,6184,6778,7308
3,912,1784,2490,3246,4182,4890,5668,6404,7290,8184,8922,9712
4,1134,2046,3124,4198,5112,6068,7086,8048,9134,10184,11130,12134
5,1308,2490,3784,4998,6184,7344,8462,9784,10862,13564,13352,14596
6,1562,2906,4268,5798,7092,8490,9804,11356,12690,15780,15558,16886
7,1782,3246,4912,6490,8188,9784,11356,12904,15646,16468,17734,19268
8,1824,3784,5560,7304,9134,10862,12690,15624,16240,18468,19998,21668

In [76]:
print(df.mode() + df.nunique())

    1     2     3     4     5     6     7     8     9     10     11     12
0  111   253   404   505   552   632   721   821   921  1441   1200   1232
1  242   465   645   854  1064  1254  1440  1681  1901  2353   2280   2454
2  353   664   934  1264  1574  1852  2143  2508  2790  3101   3398   3663
3  465   901  1254  1632  2100  2454  2843  3211  3654  4101   4470   4865
4  576  1032  1571  2108  2565  3043  3552  4033  4576  5101   5574   6076
5  663  1254  1901  2508  3101  3681  4240  4901  5440  6791   6685   7307
6  790  1462  2143  2908  3555  4254  4911  5687  6354  7899   7788   8452
7  900  1632  2465  3254  4103  4901  5687  6461  7832  8243   8876   9643
8  921  1901  2789  3661  4576  5440  6354  7821  8129  9243  10008  10843

In [77]:
(df.mode() + df.var())

,1,2,3,4,5,6,7,8,9,10,11,12
0,83132.611111,302968.5,680938.25,1.200193e+06,1897944.5,2.731682e+06,3.712220e+06,5.314241e+06,6.459500e+06,7881356.0,9.080486e+06,1.081102e+07
1,83263.611111,303180.5,681179.25,1.200542e+06,1898456.5,2.732304e+06,3.712939e+06,5.315101e+06,6.460480e+06,7882268.0,9.081566e+06,1.081224e+07
2,83374.611111,303379.5,681468.25,1.200952e+06,1898966.5,2.732902e+06,3.713642e+06,5.315928e+06,6.461369e+06,7883016.0,9.082684e+06,1.081345e+07
3,83486.611111,303616.5,681788.25,1.201320e+06,1899492.5,2.733504e+06,3.714342e+06,5.316631e+06,6.462233e+06,7884016.0,9.083756e+06,1.081465e+07
4,83597.611111,303747.5,682105.25,1.201796e+06,1899957.5,2.734093e+06,3.715051e+06,5.317453e+06,6.463155e+06,7885016.0,9.084860e+06,1.081586e+07
5,83684.611111,303969.5,682435.25,1.202196e+06,1900493.5,2.734731e+06,3.715739e+06,5.318321e+06,6.464019e+06,7886706.0,9.085971e+06,1.081709e+07
6,83811.611111,304177.5,682677.25,1.202596e+06,1900947.5,2.735304e+06,3.716410e+06,5.319107e+06,6.464933e+06,7887814.0,9.087074e+06,1.081824e+07
7,83921.611111,304347.5,682999.25,1.202942e+06,1901495.5,2.735951e+06,3.717186e+06,5.319881e+06,6.466411e+06,7888158.0,9.088162e+06,1.081943e+07
8,83942.611111,304616.5,683323.25,1.203349e+06,1901968.5,2.736490e+06,3.717853e+06,5.321241e+06,6.466708e+06,7889158.0,9.089294e+06,1.082063e+07

In [78]:
(df.mode() + df.round())

,1,2,3,4,5,6,7,8,9,10,11,12
0,204,488,790,992,1086,1246,1424,1624,1824,2864,2382,2446
1,466,912,1272,1690,2110,2490,2862,3344,3784,4688,4542,4890
2,688,1310,1850,2510,3130,3686,4268,4998,5562,6184,6778,7308
3,912,1784,2490,3246,4182,4890,5668,6404,7290,8184,8922,9712
4,1134,2046,3124,4198,5112,6068,7086,8048,9134,10184,11130,12134
5,1308,2490,3784,4998,6184,7344,8462,9784,10862,13564,13352,14596
6,1562,2906,4268,5798,7092,8490,9804,11356,12690,15780,15558,16886
7,1782,3246,4912,6490,8188,9784,11356,12904,15646,16468,17734,19268
8,1824,3784,5560,7304,9134,10862,12690,15624,16240,18468,19998,21668

In [79]:
(df.mode() + df.abs())

,1,2,3,4,5,6,7,8,9,10,11,12
0,204,488,790,992,1086,1246,1424,1624,1824,2864,2382,2446
1,466,912,1272,1690,2110,2490,2862,3344,3784,4688,4542,4890
2,688,1310,1850,2510,3130,3686,4268,4998,5562,6184,6778,7308
3,912,1784,2490,3246,4182,4890,5668,6404,7290,8184,8922,9712
4,1134,2046,3124,4198,5112,6068,7086,8048,9134,10184,11130,12134
5,1308,2490,3784,4998,6184,7344,8462,9784,10862,13564,13352,14596
6,1562,2906,4268,5798,7092,8490,9804,11356,12690,15780,15558,16886
7,1782,3246,4912,6490,8188,9784,11356,12904,15646,16468,17734,19268
8,1824,3784,5560,7304,9134,10862,12690,15624,16240,18468,19998,21668

###df.nunique com a funcao dupla da matematica

In [80]:
print(df.nunique() + df.median())

1      576.0
2     1032.0
3     1571.0
4     2108.0
5     2565.0
6     3043.0
7     3552.0
8     4033.0
9     4576.0
10    5101.0
11    5574.0
12    6076.0
dtype: float64

In [81]:
print(df.nunique() + df.count())

1     18
2     18
3     18
4     18
5     18
6     18
7     18
8     18
9     18
10    18
11    18
12    18
dtype: int64

###funcao matematica com numpy e importacao da biblioteca numpy

In [82]:
import numpy as np

In [83]:
print(df)

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [84]:
np.median(df)

np.float64(2527.5)

In [85]:
np.mean(df)

np.float64(3340.8611111111113)

In [86]:
np.argmax(df)

np.int64(107)

In [87]:
np.argmin(df)

np.int64(0)

In [88]:
print(np.sum(df))

1      4940
2      9483
3     14025
4     18613
5     23109
6     27430
7     31810
8     37043
9     41516
10    48192
11    50198
12    54454
dtype: int64

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

In [89]:
print(np.std(df))

1      271.670734
2      518.737356
3      777.770746
4     1032.665101
5     1298.683607
6     1558.078359
7     1816.347441
8     2173.257486
9     2396.031508
10    2646.578336
11    2840.859851
12    3099.791359
dtype: float64

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

In [90]:
print(np.var(df))

1     7.380499e+04
2     2.690884e+05
3     6.049273e+05
4     1.066397e+06
5     1.686579e+06
6     2.427608e+06
7     3.299118e+06
8     4.723048e+06
9     5.740967e+06
10    7.004377e+06
11    8.070485e+06
12    9.608706e+06
dtype: float64

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4006: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

In [91]:
print(np.round(df))

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834

In [92]:
print(df)

    1     2     3     4     5     6     7     8     9     10    11     12
0  102   244   395   496   543   623   712   812   912  1432  1191   1223
1  233   456   636   845  1055  1245  1431  1672  1892  2344  2271   2445
2  344   655   925  1255  1565  1843  2134  2499  2781  3092  3389   3654
3  456   892  1245  1623  2091  2445  2834  3202  3645  4092  4461   4856
4  567  1023  1562  2099  2556  3034  3543  4024  4567  5092  5565   6067
5  654  1245  1892  2499  3092  3672  4231  4892  5431  6782  6676   7298
6  781  1453  2134  2899  3546  4245  4902  5678  6345  7890  7779   8443
7  891  1623  2456  3245  4094  4892  5678  6452  7823  8234  8867   9634
8  912  1892  2780  3652  4567  5431  6345  7812  8120  9234  9999  10834